name = "Honeycomb"
uuid = "cedd129b-f94e-4a29-89a8-f3841225f99f"
authors = ["Rafael Mohr <rafael.mohr@lip6.fr>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
OscarHomotopyContinuation = "c41f96c7-3954-4cb9-9eff-e5f7ee76eb29"

[compat]
Distributions = "0.25.119"
HomotopyContinuation = "2.11.0"
Oscar = "1.3.1"
OscarHomotopyContinuation = "0.1.0"
