# Author: Simon Telen
# Date: September 15, 2026
#
# This file contains code accompanying Chapter 1 in the book
# "Toric Geometry: Theory and Practice".

using Oscar

# Example 1.2.8:
# Compute the Smith normal form of the matrix from Example 1.1.7.
# The invariant factors are obtained with diagonal(S).

A = [1 1 1 0 0 0;
     0 0 0 1 1 1;
     1 0 0 1 0 0;
     0 1 0 0 1 0;
     0 0 1 0 0 1];

A = matrix_space(ZZ, size(A)...)(A)
S, P, Q = snf_with_transform(A)
diagonal(S)

# Example 1.3.8:
# Compute the toric ideal associated with the 3-by-7 matrix in (1.3.1).
# Oscar's toric_ideal function takes the transpose of the exponent matrix.

A = [2 2 1 0 0 1 1;
     1 0 0 1 2 2 1;
     0 1 2 2 1 0 1];

IA = toric_ideal(transpose(A))

# The columns of B form an integer basis for ker(A).  Each column gives
# a binomial whose exponent difference lies in ker(A), as in Exercise 1.3.6.

x = gens(base_ring(IA))
B = nullspace(matrix_space(ZZ, size(A)...)(A))[2]

# Form the binomial ideal generated by the four binomials arising from B:
# positive and negative entries of a kernel vector give the two monomials.

J = ideal([
    prod(x .^ (B[:, i] .* (B[:, i] .> 0))) -
    prod(x .^ (-B[:, i] .* (B[:, i] .< 0)))
    for i = 1:4
])

# Exercise 1.3.6 states that saturating this binomial ideal by the product
# of all coordinates removes the extra coordinate components and recovers IA.

saturation(J, ideal(prod(x))) == IA