# Author: Simon Telen
# Date: September 15, 2026
#
# This file contains code accompanying Chapter 4 in the book
# "Toric Geometry: Theory and Practice".

using Oscar

# Example 4.5.16:
# Implement the lattice index, subdiagram volume, and multiplicity formulas
# from Definitions 4.5.1 and 4.5.3 and Theorem 4.5.8.

# Compute a matrix whose columns form a basis of the lattice generated by
# the columns of A.
function get_lattice_basis(A)
    S, P, Q = snf_with_transform(A)
    return inv(P) * S[:, 1:rank(A)]
end

# Compute a basis for the sublattice of ZA obtained by intersecting ZA
# with the linear span generated by the columns of L.
function sublattice_in_linspace(A, L)
    N = nullspace(transpose(L))[2]
    V = nullspace(transpose(N) * A)[2]
    return get_lattice_basis(A * V)
end

# Compute the lattice index i(τ,A) from Definition 4.5.1.
function get_face_lattice_index(τ, A)
    inds = findall(i -> A[:, i] in τ, 1:size(A, 2))
    L = A[:, inds]
    Rτ = sublattice_in_linspace(A, L)
    newA = solve(Rτ, A[:, inds]; side = :right)
    return get_lattice_index(newA)
end

# Compute the index of the lattice generated by the columns of A.
function get_lattice_index(A)
    return prod(diagonal(snf(A))[1:size(A, 1)])
end

# Compute the subdiagram volume from Definition 4.5.3.
function SDV(A)
    A = A[:,findall(i->sum(abs.(A[:,i]))!=0, 1:size(A,2))]
    d, n = size(A)
    Awith0 = zero(matrix_space(ZZ, d, n + 1))
    Awith0[:, 2:end] = A
    V1 = volume(convex_hull(transpose(Awith0)))
    V2 = volume(convex_hull(transpose(A)))
    vol = V1 - V2
    return factorial(d) * vol / get_lattice_index(A)
end

# Compute the multiplicity of the affine toric variety Y_A along the
# stratum associated with the face τ, using Theorem 4.5.8.
function get_multiplicity(τ, A)
    A = matrix_space(ZZ, size(A)...)(A)
    A = hcat(matrix_space(ZZ, size(A, 1), 1)(zeros(Int, size(A, 1))), A)
    inds = findall(i -> A[:, i] in τ, 1:size(A, 2))
    B = nullspace(transpose(A[:, inds]))[2]
    Amodτ = transpose(B) * A
    return get_face_lattice_index(τ, A) * SDV(Amodτ)
end

# Compute the multiplicity of the projective toric variety X_A along the
# orbit X^∘_{A,Q} corresponding to a face Q of Conv(A).
function get_multiplicity_proj(A, Q)
    if dim(Q) == 0
        At = matrix_space(ZZ, size(A)...)(A .- Array(lattice_points(Q)[1]))
        return get_multiplicity([zeros(Int, size(A, 1))], At)
    else
        Qinds = findall(p -> A[:, p] in Q, 1:size(A, 2))
        vtcs = vertices(convex_hull(transpose(A)))

        # Choose a vertex of Conv(A) contained in Q and work in its affine chart.
        vtx = vtcs[findfirst(v -> v in Q, vtcs)]
        At = matrix_space(ZZ, size(A)...)(A .- Array(vtx))
        Qt = A[:, Qinds] .- Array(vtx)
        τQ = positive_hull([Qt[:, j] for j = 1:size(Qt, 2)])
        return get_multiplicity(τQ, At)
    end
end

# Whitney's umbrella from Examples 4.5.2 and 4.5.12.
A = [1 1 0;
     0 1 2]

# The ray τ from Figure 4.2.
τ = positive_hull(A[:, 3])

# The multiplicity along τ is 2: 
get_multiplicity(τ, A)

# Example 4.5.15:
# Compute the multiplicity of X_A along every face of Conv(A).

A = [0 1 1 2;
     0 1 2 1]

P = convex_hull(transpose(A))

for i = 0:dim(P)
    println("faces of dimension $i:")
    for Q in faces(P, i)
        println(get_multiplicity_proj(A, Q))
    end
end